fix(deps): update dependency flat to v6 (#579)
* fix(deps): update dependency flat to v6

* Change import of flatten

* Use import for flatten

Resolves error:

`Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/google-cloudevents/google-cloudevents/tools/proto2jsonschema/node_modules/flat/index.js from /home/runner/work/google-cloudevents/google-cloudevents/tools/proto2jsonschema/postgen.js not supported.
Instead change the require of index.js in /home/runner/work/google-cloudevents/google-cloudevents/tools/proto2jsonschema/postgen.js to a dynamic import() which is available in all CommonJS modules.`

* Undo changes to postgen.js

* Use import in postgen.js

* set type to module package.json

* resolve __dirname error

ReferenceError: __dirname is not defined in ES module scope

---------

Co-authored-by: Roger Martinez <31829545+rogerthatdev@users.noreply.github.com>